references: &golang-image
    docker:
      - image: cimg/go:1.18

version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  download_go_modules:
    <<: *golang-image
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  tests:
    <<: *golang-image
    steps:
        - checkout
        - run:
            name: Run vet
            command: go vet ./...
        - run:
            name: Run tests
            command: make test
  build:
    <<: *golang-image
    steps:
        - checkout
        - run:
            name: Build go
            command: go build
        - run:
            name: Create a temporary directory for artifacts
            command: |
                mkdir -p /tmp/artifacts
        - run:
            name: Generate coverage
            command: |
                make test-cover
        - codecov/upload:
            file: ./c.out

workflows:
    version: 2
    build_and_tests:
      jobs:
        - download_go_modules
        - tests:
            requires:
              - download_go_modules
        - build
